import Image from "next/image";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import Banner from "../assets/images/Banner.png";
import { toast } from "react-toastify";
import Head from "next/head";
import axios from "axios";
import { User } from "../Models";
import { Avatar, Box, Button, Checkbox, Container, CssBaseline, FormControl, Grid, InputLabel, MenuItem, Select, TextField, Typography } from '@mui/material';
import { AiFillLock } from "react-icons/ai";

interface State {
  email: string
  firstName: string
  lastName: string
  password: string
  role: any
  users: User[],
}


const Signup = () => {
  const [state, setState] = useState<State>({
    email: "",
    firstName: "",
    lastName: "",
    password: "",
    role: "",
    users: [],
  });
  const { email, firstName, lastName, password, role, users } = state;

  useEffect(() => {
    axios.get("/api/users")
      .then(res => setState({ ...state, users: res.data.users }))
  }, [])

  const handleSubmit = (e: any) => {
    e.preventDefault();
    const checkEmail = users.some(user => user.email === email)
    if (checkEmail) {
      toast.info("Email đã tồn tại", {
        autoClose: 3000,
        theme: "colored",
      });
    } else if (!email || !firstName || !lastName || !password || !role) {
      toast.info("Vui lòng nhập đầy đủ thông tin", {
        autoClose: 3000,
        theme: "colored",
      });
    } else {
      axios.post("api/users", { email, password, firstName, lastName, role, balance: 0, banks: [], cart: [] })
      toast.success("Đăng ký thành công", {
        autoClose: 3000,
        theme: "colored",
      });
      setState({ ...state, firstName: "", lastName: "", password: "", email: "", role: "" })
    };
  }


  return (
    <>
      <Head>
        <title>Signup - Sport Yard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/goal.png" />
      </Head>
      <div className="h-screen bg-gray-100 overflow-hidden">
        <Grid container spacing={2}>
          <Grid item xs={0} lg={6}>
            <Container component="main" maxWidth="xs">
              <CssBaseline />
              <Box
                sx={{
                  marginTop: 8,
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                }}
              >
                <Link href="/" passHref>
                  <Grid className="group cursor-pointer" container justifyContent={"center"} alignItems={"center"} >
                    <Grid className="lg:block hidden" item xs={0} md={0} lg={3}>
                      <Image className="object-cover" src={require("../assets/images/goal.png")} />
                    </Grid>
                    <Grid item xs={0} md={12} lg={6}>
                      <Typography fontSize={30} className="  text-primary" variant="body2" component="main">
                        Sport Yard
                      </Typography>
                    </Grid>
                  </Grid>
                </Link>
                <Avatar
                  className="bg-primary"
                  sx={{ m: 1 }}>
                  <AiFillLock />
                </Avatar>
                <Typography component="h1" variant="h5">
                  Sign up
                </Typography>
                <Box component="form" noValidate onSubmit={handleSubmit} sx={{ mt: 3 }}>
                  <Grid container spacing={2}>
                    <Grid item xs={12} sm={6}>
                      <TextField
                        value={firstName}
                        onChange={e => setState({ ...state, firstName: e.target.value })}
                        autoComplete="given-name"
                        name="firstName"
                        required
                        fullWidth
                        id="firstName"
                        label="First Name"
                        autoFocus
                      />
                    </Grid>
                    <Grid item xs={12} sm={6}>
                      <TextField
                        value={lastName}
                        onChange={e => setState({ ...state, lastName: e.target.value })}
                        required
                        fullWidth
                        id="lastName"
                        label="Last Name"
                        name="lastName"
                        autoComplete="family-name"
                      />
                    </Grid>
                    <Grid item xs={12}>
                      <TextField
                        value={email}
                        onChange={e => setState({ ...state, email: e.target.value })}
                        required
                        fullWidth
                        id="email"
                        label="Email Address"
                        name="email"
                        autoComplete="email"
                      />
                    </Grid>
                    <Grid item xs={12}>
                      <TextField
                        value={password}
                        onChange={e => setState({ ...state, password: e.target.value })}
                        required
                        fullWidth
                        name="password"
                        label="Password"
                        type="password"
                        id="password"
                        autoComplete="new-password"
                      />
                    </Grid>
                    <Grid item xs={12}>
                      <FormControl fullWidth>
                        <InputLabel id="demo-simple-select-label">Role</InputLabel>
                        <Select
                          labelId="demo-simple-select-label"
                          label="Role"
                          onChange={e => setState({ ...state, role: e.target.value })}
                          role={role}
                        >
                          <MenuItem value={"customer"}>Customer</MenuItem>
                          <MenuItem value={"owner"}>Owner</MenuItem>
                        </Select>
                      </FormControl>
                    </Grid>
                  </Grid>
                  <Button
                    className="bg-[#1976dE]"
                    type="submit"
                    fullWidth
                    variant="contained"
                    sx={{ mt: 3, mb: 2 }}
                  >
                    Sign Up
                  </Button>
                  <Grid container justifyContent="flex-end">
                    <Grid item>
                      <Grid container columnGap={1} alignItems={"center"}>
                        <Grid item>
                          <Typography variant="body1" component="h6">
                            Already have an account
                          </Typography>
                        </Grid>
                        <Grid item>
                          <Link href="/signin">
                            <a className="text-[#1976dE] font-semibold">
                              ? Signin
                            </a>
                          </Link>
                        </Grid>
                      </Grid>
                    </Grid>
                  </Grid>
                </Box>
              </Box>
            </Container>
          </Grid>
          <Grid item xs={12} lg={6}>
            <Image
              className="lg:translate-y-[-10rem] h-[10rem]"
              alt="Banner"
              src={Banner}
              layout="intrinsic"
              objectFit="cover"
            />
          </Grid>
        </Grid>
      </div>
    </>
  );
};

export default Signup;
